[package]
name = "system_ladder"
version = "0.1.0"
authors = ["antlord <antlord92@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
inotify = "0.8.2"
inotify-sys = "0.1.3"

[profile.dev]
opt-level = 0
debug = true
